#include <stdio.h>

#include "abc/PRO.h"
#include "abc/S.h"
#include "dog/VERSN.h"

//  Generated by dog/version.cmake at build time; defines the three
//  VERSN_BUILD_* string literals.  Private to this TU.
#include "VERSN_BUILD.h"

//  Compile-time const slices over the generated literals.  u8slit uses
//  sizeof (no strlen), so these are valid file-scope initializers.
u8 const *VERSNVersion[2] = u8slit(VERSN_BUILD_VERSION);
u8 const *VERSNHash[2]    = u8slit(VERSN_BUILD_HASH);
u8 const *VERSNDate[2]    = u8slit(VERSN_BUILD_DATE);

ok64 VERSNu8sFeed(u8s into, u8csc prog) {
    sane($ok(into));
    a_cstr(sp, " ");
    a_cstr(op, " (");
    a_cstr(cp, ") ");
    if (!$empty(prog)) {
        call(u8sFeed, into, prog);
        call(u8sFeed, into, sp);
    }
    call(u8sFeed, into, VERSNVersion);
    call(u8sFeed, into, op);
    call(u8sFeed, into, VERSNHash);
    call(u8sFeed, into, cp);
    call(u8sFeed, into, VERSNDate);
    done;
}

ok64 VERSNReport(u8csc prog) {
    sane(1);
    if (!$empty(prog)) printf(U8SFMT " ", u8sFmt(prog));
    printf(U8SFMT " (" U8SFMT ") " U8SFMT "\n",
           u8sFmt(VERSNVersion), u8sFmt(VERSNHash), u8sFmt(VERSNDate));
    done;
}
